SET SERVEROUTPUT ON;
ACCEPT entrada PROMPT 'Introduce una numero real por teclado';

DECLARE
    vNumero NUMBER(3,2):=('&entrada');
BEGIN
    
    IF vNumero>=0 AND vNumero<5 THEN DBMS_OUTPUT.PUT_LINE('INSUFICIENTE');
    ELSIF vNumero>=5 AND vNumero<6 THEN DBMS_OUTPUT.PUT_LINE('APROBADO');
    ELSIF vNumero>=6 AND vNumero<7 THEN DBMS_OUTPUT.PUT_LINE('BIEN');
    ELSIF vNumero>=7 AND vNumero<9 THEN DBMS_OUTPUT.PUT_LINE('NOTABLE');
    ELSIF vNumero BETWEEN 9 AND 10 THEN DBMS_OUTPUT.PUT_LINE('SOBRESALIENTE');
    ELSE DBMS_OUTPUT.PUT_LINE('NOTA NO VALIDA');
    END IF;
END;