SET SERVEROUTPUT ON;
DECLARE
    vCaro PRODUCTOS.PRECIO%TYPE;
    vNombreFabricante FABRICANTES.NOMBRE%TYPE;
BEGIN
SELECT PRODUCTOS.PRECIO,FABRICANTES.NOMBRE INTO vCaro,vNombreFabricante FROM PRODUCTOS,FABRICANTES WHERE FABRICANTES.ID = PRODUCTOS.ID_FABRICANTE AND PRODUCTOS.PRECIO = (SELECT MAX(PRODUCTOS.PRECIO) FROM PRODUCTOS);
DBMS_OUTPUT.PUT_LINE('FABRICANTE: '|| vNombreFabricante || 'PRECIO: ' || vCaro);
END;
/

